- name: add mesa repo
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:kisak/kisak-mesa"
    state: present

- name: install apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 600
    state: latest
    name:
      - build-essential
      - chrome-gnome-shell
      - curl
      - fd-find
      - fzf
      - gnome-tweaks
      - gnupg
      - jq
      - kitty
      - openjdk-17-jdk
      - python3-pip
      - python3-venv
      - ripgrep
      - software-properties-common
      - tmux
      - xcape
      - xclip

- name: install snaps
  become: true
  snap:
    name:
      - slack
      - spotify
      - todoist
      - vlc

- name: install snaps with --classic
  become: true
  snap:
    classic: true
    name:
      - intellij-idea-ultimate
      - nvim
      - sublime-merge

- name: docker
  become: true
  block:
    - name: add gpg key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        keyring: "/etc/apt/trusted.gpg.d/docker.gpg"

    - name: add repo for ubuntu 22.04
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"
        state: present
        filename: docker
      when: ansible_distribution_release == "jammy"

    - name: install docker packages
      ansible.builtin.apt:
        name:
          - docker-ce 
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        force_apt_get: yes

- name: setup fonts
  block:
    - name: create local fonts directory
      ansible.builtin.file:
        path: "~{{ local_username }}/.local/share/fonts"
        state: directory

    - name: install FiraCode font
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/FiraCode.zip"
        dest: "~{{ local_username }}/.local/share/fonts"
        remote_src: yes

    - name: refresh fonts cache
      ansible.builtin.shell: "fc-cache -fv"
      become: true

- name: hashicorp
  become: true
  block:
    - name: add apt key
      ansible.builtin.apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        keyring: "/etc/apt/trusted.gpg.d/hashicorp.gpg"

    - name: add repo for ubuntu 22.04
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com jammy main"
        state: present
        filename: hashicorp
      when: ansible_distribution_release == "jammy"

    - name: prioritize packages from hashicorp apt repo
      ansible.builtin.copy:
        src: etc/apt/preferences.d/hashicorp.pref
        dest: /etc/apt/preferences.d/hashicorp.pref
        owner: root
        group: root
        mode: 0644

    - name: install hashicorp packages
      ansible.builtin.apt:
        name:
          - terraform
        force_apt_get: yes

