- name: install apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 600
    state: latest
    name:
      - zsh
      - zsh-antigen
      - zsh-doc

- name: change user's shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ local_username }}"
    shell: /bin/zsh
